# Generated by Django 3.1.4 on 2021-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210125_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='bio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
